name: 'changelog'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      uses: nielstenboom/changelog-generator@main
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        head-ref: 'v0.1.0'
        base-ref: 'v1.0.0'

    - name: Get the changelog
      run: |
        cat << "EOF"
        ${{ steps.changelog.outputs.changelog }}
        EOF
