name: 'changelog'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      uses: nielstenboom/semantic-changelog-generator@d8c4d06
      with:
        base: 'v0.1.0'
        head: 'origin/niels/test-action'

    - name: Get the changelog
      run: |
        cat << "EOF"
        ${{ steps.changelog.outputs.changelog }}
        EOF
