name: 'changelog'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      uses: nielstenboom/changelog-generator@7da305c18b42b7e0ef3f49bbd6f8d670cd3c192f
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        head-ref: 'niels/test-action'
        base-ref: 'v1.0.0'

    - name: Get the changelog
      run: |
        cat << "EOF"
        ${{ steps.changelog.outputs.changelog }}
        EOF
