name: 'test'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.6"
    
    - run: |
        conda install nomkl faiss-cpu=1.6.3 -c pytorch
        conda remove mkl mkl-service
        python --version
        pip install .
        pip uninstall recurring_content_detector -y
        python -m pytest -s