name: 'test'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.7"
    
    - run: |
        pip install .
        sudo apt-get update
        sudo apt-get install libglib2.0-0 -y
        sudo apt-get install libsm6 libxext6 libxrender-dev -y
        conda install faiss-cpu=1.7.2 -c pytorch
        pip uninstall recurring_content_detector -y
        python -m pytest -s
