name: 'test'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
    
    - run: |
        python --version
        pip install .
        python -m pytest