name: 'changelog'
on: 'pull_request'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - uses: actions/checkout@v3

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@e032df570a1247a77fe9f2a7d003979181bc8bb1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        head-ref: 'niels/test-action'
        base-ref: 'v1.0.0'

    - name: Get the changelog
      run: |
        cat << "EOF"
        ${{ steps.changelog.outputs.changelog }}
        EOF
